name: 'Lock down repository'

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  # schedule:
  #   - cron: '0 0 * * SUN'

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue: true
          lock-issue: true
          issue-comment: >
            This repository does not accept issues,
            see the README for details.
          skip-closed-issue-comment: false
          issue-lock-reason: ''

          exclude-pr-created-before: ''
          exclude-pr-labels: ''
          close-pr: true
          lock-pr: true
          pr-comment: >
            This repository does not accept pull requests,
            see the README for details.
          pr-labels: ''
          skip-closed-pr-comment: false
          pr-lock-reason: ''
